### ISSUE TITLE
Not all taxa downloaded

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#12]
According to the [download list](https://github.com/trias-project/pipeline/blob/master/data/output/gbif_downloads.tsv), last GBIF download (https://doi.org/10.15468/dl.9unif7) used the [eu_concern_species.tsv](https://github.com/trias-project/pipeline/commit/fd431ef52b1adf5dbcb25626d66cc3c675f177c8) list to query for taxa. However, only 38 of the 49 species are queried. These are 11 missing:

checklist_scientificName | backbone_taxonKey
--- | ---
Alopochen aegyptiacus | 2498252
Elodea nuttallii | 5329212
Gunnera tinctoria | 2984306
Heracleum mantegazzianum | 3034825
Heracleum persicum | 3628745
Myriophyllum aquaticum | 5361785
Myriophyllum heterophyllum | 5361762
Parthenium hysterophorus | 3086784
Pennisetum setaceum | 2706134
Persicaria perfoliata | 4033648
Pueraria lobata | 9035634

@damianooldoni can you figure out what might cause this? Is it a character limit on the querystring in the URL?

**Comment by damianooldoni** [comment]
Thanks @peterdesmet to check the pipeline and start this issue! 
I see that the problem is at the very beginning of the workflow:
```r
input_checklist <- "../data/input/eu_concern_species.tsv"
eu_concern_species <- read.table(file = input_checklist, 
                                 header = TRUE, sep = "\t")
```
The returned `eu_concern_species` variable has 38 rows instead of 49!
The problem is solved by using the code here below:
```r
library(readr)
eu_concern_species <- 
  read_delim("../data/input/eu_concern_species.tsv", 
             "\t", escape_double = FALSE, 
             col_types = cols(
               entry_into_force = col_date(
                 format = "%Y-%m-%d")), 
             trim_ws = TRUE)

```
code generated automatically using graphic RSTUDIO data import interface.
Just checked with a new download request and the downloaded dataframe contains 48 out of 49 taxonKey, tested via this line:
```r
length(unique(test$taxonKey))
```
A commit very soon.

**Comment by damianooldoni** [comment]
Thanks to this issue, I found another error:
the loop in function `update_download_list.R` (from `trias` repository ) to check whether downloads in `PREPARING` or  `RUNNING` status changed status to `SUCCEDDED`or `FAILED` was like this one:
``` r
for (i in 1:length(downloads))`
```
which is bad, because `length(df)` gives back the number of columns instead of rows! 
It should be: 
```r
for (i in 1:nrow(downloads))
```
Time to commit!!

**Comment by damianooldoni** [comment]
Previous problems are tackled in the following commits:
import correctly the species from a file in table:
e88ec4866ef7ec7bc35489a9f7739ee7406c2702
loop in `update_download_list.R` function from `trias` package:
https://github.com/trias-project/trias/commit/f48d845ecb16e388c1a86ddd05407b7926680569

**Comment by peterdesmet** [comment]
Retested and rewrote the pipeline. Pull request coming up.
